api/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


app_name = 'api'

urlpatterns = [
    path('statistical-anaylsis/<str:product_type>/<str:title>/', views.statistical_analysis, name='statistical-analysis'),
    path('brochure-templates/<str:product_type>/', views.brochure_templates, name='brochure-templates'),

    path('users/<str:username>/products/', views.UserProductsView.as_view(), name='user-products'), #
    path('users/<str:username>/orders/', views.UserOrdersView.as_view(), name='user-orders'), #
    path('users/<str:username>/orders/recent/', views.UserRecentOrdersView.as_view(), name='user-recent-orders'), #
    path('users/<str:username>/brochures/', views.UserBrochureView.as_view(), name='user-brochures'), #
    path('users/<str:username>/market/', views.UserMarketingResults.as_view(), name='user-market'), #

    path('products/<int:product_id>/orders/', views.ProductOrdersView.as_view(), name='product-orders'),
    # path('products/<int:product_id>/feedback/', views.UserProductFeedbackView.as_view(), name='product-feedback'),
    path('products/<int:product_id>/<str:activity_type>/', views.product_activity, name='product-activity'),

    path('products/', views.ProductListView.as_view(), name='products'),
    path('orders/', views.OrdersView.as_view(), name='orders'),
    path('users/', views.UserListView.as_view(), name='users'),
    path('brochures/', views.BrochureListView.as_view(), name='brochures'),
    path('market/', views.MarketingResultsListView.as_view(), name='market-results'),
]

buyer/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'buyer'

urlpatterns = [
    path('client_dashboard/', views.client_dashboard, name='dashboard'),
    path('buy_product/<int:price_package_id>/', views.buy_product, name='buy-product'),
    path('feedback/<int:bought_package_id>/', views.give_feedback, name='give-feedback'),
]

core/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('redirect/', views.redirect_users, name='redirect'),
    path('explore/', views.explore, name='explore'),
    path('billing/', views.billing, name='billing'),
    path('about-us/', views.about, name='about-us'),
    path('notifications/', views.notifications, name='notifications'),

    path('product/search/', views.search_product, name='product-search'),
    path('product/<str:slug>/', views.view_product, name='product-view'),

    path('user/<str:username>/', views.view_user, name='user-view'),

    path('plan/', views.project_plan, name='project_plan'),
    path('stripe/webhook/', views.stripe_webhook, name='stripe_webhook'),

    path('admins/product/review/', views.admins_product_reivew, name='admin-product-review'),
    path('admins/dashboard/', views.admin_dashboard_view, name='admin-dashboard'),

    path('analysis/product/<int:product_id>/', views.product_analysis_view, name='product-analysis'),
    path('analysis/user/<str:username>/', views.user_analysis_view, name='user-analysis'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('accounts.urls')),
    path('', include('core.urls')),
    path('', include('seller.urls')),
    path('', include('buyer.urls')),
    path('', include('market.urls')),

    path('api/v1/', include('api.urls')),

    path('tinymce/', include('tinymce.urls')),

    path(
        'reset_password/',
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html'
        ),
        name="reset_password"
    ),
    path(
        'reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_sent.html'
        ),
        name="password_reset_done"
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_form.html'
        ),
        name="password_reset_confirm"
    ),
    path(
        'reset_password_complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name="password_reset_complete"
    ),
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='accounts/change_password.html',
            success_url = '/'
        ),
        name='change_password'
    ),


]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

core/models.py
import re
import requests
from bs4 import BeautifulSoup
from datetime import datetime
import base64
from tinymce.models import HTMLField

from django.utils.timezone import now
from django.db import models
from django.core.files.base import ContentFile
from django.core.files.images import ImageFile
from django.contrib.auth.models import AbstractBaseUser, \
                                        PermissionsMixin
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model that suppors using email instead of username"""
    email = models.EmailField(max_length=255, unique=True)
    username = models.CharField(max_length=25, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    wallet = models.PositiveIntegerField(default=0)
    mode = models.CharField(choices=(
        ('S', 'seller'),
        ('B', 'buyer'),
    ), default='S', max_length=1)

    objects = UserManager()
    joining_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    USERNAME_FIELD = 'username'

    def __str__(self):
        return f"{self.id} | {self.username} | {self.mode}"

    def package_already_bought(self, package_id):
        return ClientPackages.objects.filter(
            user=self,
            package__id=package_id
        ).exists()


PRODUCT_TYPES = (
    ('A', 'API'),
    ('L', 'Logo'),
    ('H', 'TEMPLATE'),
    ('D', 'Software'), # desktop or mobile application.
)


class Category(models.Model):
    product_type = models.CharField(choices=PRODUCT_TYPES, default='A', max_length=1)
    name = models.CharField(max_length=500)

    def __str__(self):
        return f"{self.product_type}: {self.name}"

    class Meta:
        db_table = "Category"


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return self.name

    class Meta:
        db_table = "Tag"

    def __str__(self):
        return f"{self.id} | {self.name}"


class Product(models.Model):
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    slug = models.CharField(default="", max_length=255, blank=True)
    description = HTMLField()
    
    thumbnail = models.ImageField('products/', null=True, blank=True)
    thumbnail_metadata = models.JSONField(null=True, blank=True)

    source_url = models.CharField(max_length=5000, null=True, blank=True)

    product_type = models.CharField(choices=PRODUCT_TYPES, default='A', max_length=1)

    last_approval_request_date = models.DateTimeField(auto_now=True)
    review_count = models.IntegerField(default=0)
    review_average = models.FloatField(default=0)

    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    marketed_on = models.ManyToManyField('MarketingPlatforms', blank=True)

    impressions = models.IntegerField(default=0)
    clicks = models.IntegerField(default=0)
    show_on_landing = models.BooleanField(default=False)

    status = models.CharField(choices=(
        ('A', 'approved'),
        ('R', 'rejected'),
        ('P', 'pending'),
        ('D', 'deleted'),
    ), default='D', max_length=1)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "Product"

    def __str__(self):
        return f"{self.id} | {self.product_type} | {self.owner.username} | {self.title}"

    def save(self, *args, **kwargs):
        self.slug = f"{self.id}-{self.title.replace(' ', '-').lower()}"

        ## SAVING IMAGE
        selected_image = [i["data"] for i in self.thumbnail_metadata if i['isPrimary']][0]
        format, imgstr = selected_image.split(';base64,')
        ext = format.split('/')[-1]
        c = ContentFile(base64.b64decode(imgstr))
        filename = "product-"+datetime.now().strftime("%Y%m%d-%H%M%S")+"." + ext
        self.thumbnail = ImageFile(c, name=filename)

        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return "/{self.user.username}/{self.slug}/"

    def get_product_obj(self):
        if self.product_type == "A":
            obj = ApiService.objects.get(product=self)
        elif self.product_type == 'L':
            obj = Logo.objects.get(product=self)
        elif self.product_type == 'H':
            obj = HtmlTemplate.objects.get(product=self)
        elif self.product_type == 'D':
            obj = DownloadSoftware.objects.get(product=self)
        return obj

    def get_description_text(self):
        return BeautifulSoup(self.description, parser='lxml', features='lxml').text

    def get_dribble_obj(self):
        return DribbleProduct.objects.filter(product=self, status='A')
    
    def get_pinterest_obj(self):
        return PinterestProduct.objects.filter(product=self, status='A')

    def get_coroflot_obj(self):
        return CoroloftProduct.objects.filter(product=self, status='A')

class Logo(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    source_file = models.FileField('logo/')
    source_file_size = models.CharField(max_length=50, null=True, blank=True)
    width = models.IntegerField(default=0, null=True, blank=True)
    height = models.IntegerField(default=0, null=True, blank=True)
    logo_type = models.CharField(choices=(
        ('PORTAIT', 'PORTAIT'),
        ('LANDSCAPE', 'LANDSCAPE'),
        ('SQUARE', 'SQUARE'),
    ), max_length=100, default='SQUARE')

    class Meta:
        db_table = "Logo"

    def __str__(self):
        return f"{self.id} | {self.product.title}"


class HtmlTemplate(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    source_file = models.FileField('templates', null=True)
    source_file_size = models.CharField(max_length=50, null=True, blank=True)
    supported_browser = models.CharField(max_length=5000, null=True, blank=True)
    demo_site = models.CharField(max_length=5000, null=True, blank=True)
    technical_instructions = HTMLField(default="", null=True, blank=True)

    class Meta:
        db_table = "HtmlTemplate"

    def __str__(self):
        return f"{self.id} | {self.product.title}"


class DownloadSoftware(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    source_file = models.FileField('software', null=True)
    source_file_size = models.CharField(max_length=50, null=True, blank=True)
    in_scope = HTMLField(default="", null=True, blank=True)
    out_scope = HTMLField(default="", null=True, blank=True)
    technical_instructions = HTMLField(default="", null=True, blank=True)
    technology = models.CharField(default="", null=True, blank=True, max_length=500)
    trail_version = models.FileField('software-trail', null=True)

    supported_os = models.CharField(max_length=500, null=True, blank=True)
    software_type = models.CharField(choices=(
        ("OFFLINE", "OFFLINE"),
        ("ONLINE", "ONLINE"),
    ), max_length=100, default='ONLINE')

    class Meta:
        db_table = "DownloadSoftware"

    def __str__(self):
        return f"{self.id} | {self.product.title}"


class ApiService(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    website_url = models.CharField(max_length=5000) # website, optional
    base_url = models.CharField(max_length=5000) # API hosted server domain path
    in_scope = HTMLField(default="", null=True, blank=True)
    out_scope = HTMLField(default="", null=True, blank=True)
    technology = models.CharField(default="", null=True, blank=True, max_length=500)
    technical_instructions = HTMLField(default="", null=True, blank=True)

    def save(self, *args, **kwargs):
        super(ApiService, self).save(*args, **kwargs)

    class Meta:
        db_table = "ApiService"

    def __str__(self):
        return f"{self.id} | {self.product.title}"


class Endpoints(models.Model):
    path = models.CharField(max_length=5000)
    documentation = HTMLField(default="", null=True, blank=True)
    service = models.ForeignKey(ApiService, on_delete=models.CASCADE)
    request_type = models.CharField(choices=(
        ('GET', 'GET'),
        ('POST', 'POST'),
        ('PATCH', 'PATCH'),
        ('PUT', 'PUT'),
        ('DELETE', 'DELETE'),
    ), default='P', max_length=6)
    request_level = models.CharField(choices=(
        ('tiny', 'tiny'),
        ('normal', 'normal'),
    ), max_length=10)
    test_data = models.TextField() # TEST json data


    class Meta:
        db_table = "Endpoints"

    def get_full_test_url(self):
        return f"{settings.API_SERVER_TEST_URL}{self.path}"

    def __str__(self):
        return f"{self.id} | {self.service.product.title} | {self.path}"


class ProductPackage(models.Model):
    service = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    price = models.IntegerField(default=0)

    tiny_requests = models.IntegerField(default=0)
    normal_requests = models.IntegerField(default=0)


    class Meta:
        db_table = "ProductPackage"

    def __str__(self):
        return f"{self.id} | {self.service.title} | {self.title}"


class ClientPackages(models.Model):
    package = models.ForeignKey(ProductPackage, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    token = models.CharField(max_length=255)
    amount_paid = models.IntegerField(default=0)

    tiny_requests_left = models.IntegerField(default=0)
    normal_requests_left = models.IntegerField(default=0)
    last_request_used = models.DateTimeField(auto_now=True)

    reactivation = models.IntegerField(default=0) # show how many times the package is reactivated.

templates/core/admin-product-review.html
{% extends 'base.html' %}
{% load static %}
{% block title %}YourSite{% endblock title %}

{% block body %}
<div class="container mt-5 ">
    <div class="my-3 p-3 bg-white rounded box-shadow col-12">
        <h3 class="border-bottom border-gray pb-2 mb-0"><strong>APPROVE/REJECT PRODUCT</strong></h3>
        <div class="row">
            {%if not products%}
                <h3 class="p-5 mb-0 col-12 text-center"><i><strong> NO NEW PRODUCTS</strong></i></h3>
            {% endif %}
            {%for product in products %}
            <div class="col-12">
                <div class="media m-3 text-muted">
                    <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" style="width: 64px; height: 64px;" src="{{product.thumbnail.url}}" data-holder-rendered="true">
                    <div class="media-body">
                        <a href="{% url 'core:product-view' product.slug %}" target=”_blank” ><h5 class="mt-0"><strong class="d-block text-gray-dark">{{product.title}}</strong></h5></a>
                        <p class="mt-0">{{product.description|safe}}</p>
                        <p class="mt-0"><strong>Created: </strong>{{product.created_at|timesince}}</p>
                        <p>
                        {% if product.product_type == 'A' %}
                        <span style="background-color: tomato;" class="badge text-white p-2">{{product.get_product_type_display.upper}}</span>
                        {% elif product.product_type == 'L' %}
                        <span style="background-color:darkgreen;" class="badge text-white p-2">{{product.get_product_type_display.upper}}</span>
                        {% elif product.product_type == 'H' %}
                        <span style="background-color:darkslateblue;" class="badge text-white p-2">{{product.get_product_type_display.upper}}</span>
                        {% elif product.product_type == 'D' %}
                        <span style="background-color:darkorange;"  class="badge text-white p-2">{{product.get_product_type_display.upper}}</span>
                        {% endif %}
                        </p>
                    </div>
                    <div class="ml-5 align-self-center px-3">
                        <form action="." method="post">{% csrf_token %}
                            <input hidden type="text" value="{{product.id}}" name="product_id">
                            <input hidden type="text" value="A" name="action">
                            <button type="submit" class="btn btn-warning font-weight-bold" style="width:100px;"><b>APPROVE</b></button>
                        </form><br>
                        <form action="." method="post">{% csrf_token %}
                            <input hidden type="text" value="{{product.id}}" name="product_id">
                            <input hidden type="text" value="R" name="action">
                            <button type="submit" class="btn btn-danger font-weight-bold" style="width:100px;"><b>REJECT</b></button>
                        </form>
                    </div>
                </div>
            </div>
            <hr>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock body %}

{% block js %}

{% endblock js %}

templates/core/billing.html
{% extends 'base.html' %}
{% load static %}
{% block title %}YourSite{% endblock title %}

{% block body %}
<div class="container">
    {% include 'components/transaction_logs.html' %}
</div>
{% endblock body %}

{% block js %}

{% endblock js %}

templates/core/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{% endblock title %}
{% block css %}
.checked {
    color: orange;
}
{% endblock css %}
{% block body %}
<div class="container-fluid">
    <nav class="navbar navbar-light">
        <a class="navbar-brand"><h1><b>Search Results for: {{query}}</b></h1></a>
        <form method='GET' action='{% url "core:product-search" %}' class="form-inline">
            <input name='query' class="form-control mr-sm-2" type="search" placeholder="" aria-label="Search" value="{{query}}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </nav>
    </div>

<br>
<div class="container-fluid">
    <div class="row">
        <div class="col-3">
            <nav class="nav flex-column bg-light "> 
                <h4><B>Filters</B></h4>
            </nav>
        </div>
        
        <div class="col-9">
            <div class="row">
                {% for product in products %}

                    {% include 'components/product/public-product-card.html'%}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="col-12">
        <ul class="pagination">
            {% for i in pages %}
            {% if i == page_number %}
                <li class="page-item active">
            {% else %}
                <li class="page-item">
            {% endif %}
                <a href="?query={{query}}&page={{i}}" class="page-link">{{i}}</a> 
            </li>
            {% endfor %}
        </ul>
    </div>
</div>    


<br>
<br>
<br>
{% endblock body %}


{% block js %}

{% endblock js %}

templates/core/view-api.html
pokemon/ditto{% extends 'base.html' %}
{% load static %}
{% block title %}YourSite{% endblock title %}

{% block body %}
<div class="container mt-5 ">
    <div class="row">
        <div class="col-9">
            <div class="card p-3 mb-3">
                <div class="media">
                    <img class="rounded-circle mr-3" src="https://images.unsplash.com/photo-1544967082-d9d25d867d66?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80" style="width:30px; height:30px;" alt=""></h6>
                    <div class="media-body">
                        <h3 class="mt-0">{{product.owner.username.title}}</h2>
                    </div>
                </div>
            </div> 
            <span class="badge badge-primary px-2 py-1">{{product.get_product_type_display}}</span>
            <h1>{{product.title.title}}</h1>
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                {% for thumbnail in product.thumbnail_metadata %}
                {% if thumbnail.isPrimary %}
                  <div class="carousel-item active">
                    <img src="{{thumbnail.data}}" class="d-block w-100" style="max-height: 400px;" alt="...">
                </div>
                {% endif %}
                {% endfor %}
                {% for thumbnail in product.thumbnail_metadata %}
                    {% if not thumbnail.isPrimary %}
                  <div class="carousel-item">
                    <img src="{{thumbnail.data}}" class="d-block w-100" style="max-height: 400px;" alt="...">
                  </div>
                {% endif %}
                {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <hr>
            {% if product.source_url %}
                <p><h3 class="text-muted font-italic"><strong>Source URL: </strong></h3>{{product.source_url}}</p>
            {% endif %}
    
            <h3 class="text-muted font-italic"><strong>Description: </strong></h3>
                {{product.description|safe}}

            {% if obj.technical_instructions %}
                <h3 class="text-muted font-italic"><strong>Technical Instructions: </strong></h3>
                {{obj.technical_instructions|safe}}
            {% endif %}

            {% if obj.in_scope %}
                <h3 class="text-muted font-italic"><strong>In Scope: </strong></h3>
                {{obj.in_scope|safe}}
            {% endif %}

            {% if obj.out_scope %}
                <h3 class="text-muted font-italic"><strong>Out Scope: </strong></h3>
                {{obj.out_scope|safe}}
            {% endif %}

            <hr>

            <hr>
        </div>
        <div class="col-3">
            {% for package in packages %}
            <div class="card mb-2 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal text-center">{{package.title}}</h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title pricing-card-title text-center">{{package.price}} USD</h5>
                    <hr>
                    <h5 class="text-center">Number Of Requests: {{package.normal_requests}}</h5>
                    <hr>
                    <a href="{% url 'buyer:buy-product' package.id %}" type="button" class="btn btn-lg btn-block btn-success">
                        {% if request.user.is_authenticated %}
                            Buy Now
                        {% else %}
                            Log In & Buy Now
                        {% endif %}
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-12">
            <div class="row">
                <div class="col-5 card">
                    <h3 class="text-muted font-italic"><u>Endpoint</u></h3><hr>
                    <table class="table border">
                        <thead>
                        </thead>
                        <tbody id="e_body">
                            {% for endpoint in endpoints %}
                            <tr>
                                <td onclick="show_endpoint_info(this)">
                                    <span class="badge badge-primary">{{endpoint.request_type}}</span>
                                    {{endpoint.path}}
                                    <input type="text" name="endpoint_request_type" value="{{endpoint.request_type}}" hidden>
                                    <input type="text" name="endpoint_url" value="{{endpoint.get_full_test_url}}" hidden>
                                    <textarea hidden name='enpoint_desc'>{{endpoint.documentation}}</textarea>
                                    <textarea hidden name='enpoint_test_data'>{{endpoint.test_data}}</textarea>
                                </td>
                                <td style="text-align:end;">
                                    <button class="btn-edit badge badge-info h-100" data-toggle="modal" data-target=".bd-example-modal-lg" onclick="test_modal(this)">TEST</button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-3 border">
                    <h3><u>Endpoint Doc.</u></h3><hr>
                    <p id="e_desc_view">{{endpoints.0.documentation}}
                    </p>
                    <!-- <textarea class="form-control mb-2" id="e_desc_view" rows="10"
                        placeholder="Endpoint Documentation" disabled></textarea> -->
                </div>
                <div class="col-4 border">
                    <h3><u>Testing Data</u></h3><hr>
                    <pre id="e_test_data_view">{{endpoints.0.test_data}}
                    </pre>
                </div>
            </div>
        </div>
        <div class="col-9">
            {% if feedbacks %}
            <h3 class="my-3">Feedback</h2>
                {% include 'components/feedback.html' %}
            {% endif %}
        </div>
    </div>
</div>
<br>
<br>
<div class="modal fade bd-example-modal-lg" id="e_modal" tabindex="-1" role="dialog"
aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">TEST ENDPOINTS</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <!-- ENDPOINT TEST MODAL -->
            <div class="modal-body" id="endpoint_modal">
                <div class="container-fluid top px-5">
                    <div class="row">
                        <div class="btn-group col-3 mb-3">
                            <select class='form-control' id="endpoint_request_type" disabled>
                                <option value="GET">GET</option>
                                <option value="POST">POST</option>
                                <option value="DELETE">DELETE</option>
                                <option value="PUT">PUT</option>
                                <option value="PATCH">PATCH</option>
                            </select>
                        </div>
                        <div class="col-9">
                            <input type="Endpoint URL" class="form-control" id="endpoint_url"
                                aria-describedby="titleHelp" placeholder="Endpoint URL">
                        </div>
                        <div class="col-12">
                            <small>NOTE: Only Content-type: application/json is acceptable</small>
                        </div>
                        <div class="col-12 mb-3">
                            <hr>
                            <h4 class="form-text text-muted desc">Headers:</h4>
                            <span><strong>Content-type: </strong>application/json</span><br>
                            <span><strong>AAAS-TOKEN: </strong>TEST-{{product.id}}</span>
                            <hr>
                        </div>
                        <div class="col-12 mb-3">
                            <h4 class="form-text text-muted desc">Request Data:</h4>
                            <textarea class="form-control" id="endpoint_test_data" rows="7"></textarea>
                            <hr>
                        </div>
                        <div class="col-12">
                            <button class="btn btn-success col-12" onclick="request_to_endpoint()">REQUEST TO ENDPOINT</button>
                        </div>
                        <div class="col-12">
                            <h4 class="form-text text-muted desc">Response</h4>
                            <!-- <span><strong>Status Code: </strong><span id="test_endpoint_status_code">200</span></span><br> -->
                                <pre id='endpoint_response' class="border" style="width: 100%;" class="p-3">
                                    
                                </pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

{% block js %}
<script>
function show_endpoint_info(el) {
    document.getElementById('e_desc_view').innerHTML = el.childNodes[7].innerHTML
    document.getElementById('e_test_data_view').innerHTML =  el.childNodes[9].innerHTML
    console.log(el.childNodes[9].innerHTML)
};

function test_modal(el) {
    obj = el.parentElement.parentElement.children[0];
    console.log(obj)
    document.getElementById('endpoint_request_type').value = obj.children[1].value;
    document.getElementById('endpoint_url').value = obj.children[2].value;
    document.getElementById('endpoint_test_data').value = obj.children[4].value;
    $('#e_modal').modal('show');
}

function request_to_endpoint() {
    console.log(document.getElementById('endpoint_test_data').value)
    $.ajax({
        type: document.getElementById('endpoint_request_type').value,
        url: document.getElementById('endpoint_url').value,
        crossDomain: true,
        headers: {
            "Content-Type": "application/json",
            "AAAS-TOKEN": "TEST-{{product.id}}"
        },
        data: document.getElementById('endpoint_test_data').value,
        success: function(data){
            document.getElementById('endpoint_response').textContent = JSON.stringify(data, null, 4);
           console.log(data)
        },
        error: function(error){
            console.log('error')
            console.log(error)
            if ("responseJSON" in error) {
                document.getElementById('endpoint_response').textContent = JSON.stringify(error.responseJSON, null, 3);
            } else {
                document.getElementById('endpoint_response').textContent = error.statusText;
            }
        }
});
}
</script>
{% endblock js %}