accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name='accounts'

urlpatterns = [
    path('register/',views.register, name='register'),
    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('user_profile/',views.user_profile, name='user_profile'),
    path('user-mode-switch/',views.user_mode_switch, name='user-mode-switch'),

]

api/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


app_name = 'api'

urlpatterns = [
    path('statistical-anaylsis/<str:product_type>/<str:title>/', views.statistical_analysis, name='statistical-analysis'),
    path('brochure-templates/<str:product_type>/', views.brochure_templates, name='brochure-templates'),

    path('users/<str:username>/products/', views.UserProductsView.as_view(), name='user-products'), #
    path('users/<str:username>/orders/', views.UserOrdersView.as_view(), name='user-orders'), #
    path('users/<str:username>/orders/recent/', views.UserRecentOrdersView.as_view(), name='user-recent-orders'), #
    path('users/<str:username>/brochures/', views.UserBrochureView.as_view(), name='user-brochures'), #
    path('users/<str:username>/market/', views.UserMarketingResults.as_view(), name='user-market'), #

    path('products/<int:product_id>/orders/', views.ProductOrdersView.as_view(), name='product-orders'),
    # path('products/<int:product_id>/feedback/', views.UserProductFeedbackView.as_view(), name='product-feedback'),
    path('products/<int:product_id>/<str:activity_type>/', views.product_activity, name='product-activity'),

    path('products/', views.ProductListView.as_view(), name='products'),
    path('orders/', views.OrdersView.as_view(), name='orders'),
    path('users/', views.UserListView.as_view(), name='users'),
    path('brochures/', views.BrochureListView.as_view(), name='brochures'),
    path('market/', views.MarketingResultsListView.as_view(), name='market-results'),
]

buyer/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'buyer'

urlpatterns = [
    path('client_dashboard/', views.client_dashboard, name='dashboard'),
    path('buy_product/<int:price_package_id>/', views.buy_product, name='buy-product'),
    path('feedback/<int:bought_package_id>/', views.give_feedback, name='give-feedback'),
]

core/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('redirect/', views.redirect_users, name='redirect'),
    path('explore/', views.explore, name='explore'),
    path('billing/', views.billing, name='billing'),
    path('about-us/', views.about, name='about-us'),
    path('notifications/', views.notifications, name='notifications'),

    path('product/search/', views.search_product, name='product-search'),
    path('product/<str:slug>/', views.view_product, name='product-view'),

    path('user/<str:username>/', views.view_user, name='user-view'),

    path('plan/', views.project_plan, name='project_plan'),
    path('stripe/webhook/', views.stripe_webhook, name='stripe_webhook'),

    path('admins/product/review/', views.admins_product_reivew, name='admin-product-review'),
    path('admins/dashboard/', views.admin_dashboard_view, name='admin-dashboard'),

    path('analysis/product/<int:product_id>/', views.product_analysis_view, name='product-analysis'),
    path('analysis/user/<str:username>/', views.user_analysis_view, name='user-analysis'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('accounts.urls')),
    path('', include('core.urls')),
    path('', include('seller.urls')),
    path('', include('buyer.urls')),
    path('', include('market.urls')),

    path('api/v1/', include('api.urls')),

    path('tinymce/', include('tinymce.urls')),

    path(
        'reset_password/',
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html'
        ),
        name="reset_password"
    ),
    path(
        'reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_sent.html'
        ),
        name="password_reset_done"
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_form.html'
        ),
        name="password_reset_confirm"
    ),
    path(
        'reset_password_complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name="password_reset_complete"
    ),
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='accounts/change_password.html',
            success_url = '/'
        ),
        name='change_password'
    ),


]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

seller/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'seller'

urlpatterns = [
    path('seller_dashboard/', views.seller_dashboard, name='dashboard'),

    path('product/create/logo/', views.create_logo, name='create-logo'),
    path('product/create/template/', views.create_template, name='create-template'),
    path('product/create/software/', views.create_software, name='create-software'),
    path('product/create/api/', views.create_api, name='create-api'),

    path('product/update/<int:product_id>/logo/', views.update_logo, name='update-logo'),
    path('product/update/<int:product_id>/template/', views.update_template, name='update-template'),
    path('product/update/<int:product_id>/software/', views.update_software, name='update-software'),
    path('product/update/<int:product_id>/api/', views.update_api, name='update-api'),

    path('product/delete/<int:product_id>/', views.delete_product, name='delete-product'),

]

templates/base.html
 <!doctype html>
<html lang="en">
    {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.10.0/jsoneditor.min.css" integrity="sha512-brXxIa/fpMfluh8HUWyrNssKy/H0oRzA0HhmipgfVwbXPamMUTZn1jEsvoGGwJYCRpSx4idujdul4vFwWgPROA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
      body {
        background-color: #f8f9fa!important;
      }
      .fa-star {
        color: orange;
      }
      {% block css %}

      {% endblock css %}
    </style>
    <title>AAAS {% block title %}{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: black;">
      <div class="container-fluid my-1">
      <a style="font-primary: 'Montserrat', sans-serif;" class="navbar-brand" href="/"><h3>AAAS<span style="color:red;">.</span></h3></a>
      <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button> -->

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            {%if request.user.mode == 'S' %}
            <a class="nav-link" href="{% url 'seller:dashboard' %}">Dashboard</a>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Create
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'seller:create-api' %}">API</a>
                <a class="dropdown-item" href="{% url 'seller:create-logo' %}">LOGO</a>
                <a class="dropdown-item" href="{% url 'seller:create-template' %}">Template</a>
                <a class="dropdown-item" href="{% url 'seller:create-software' %}">Software</a>
              </div>
            </li>
            {% elif request.user.mode == 'B' %}
            <a class="nav-link" href="{% url 'buyer:dashboard' %}">Dashboard</a>
            {% endif %}
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:billing' %}">Billing</a>
          </li>
          {% endif %}
          <!-- <li class="nav-item">
            <a class="nav-link" href="{% url 'core:explore' %}">Products</a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:explore' %}">Explore</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:about-us' %}">About Us</a>
          </li>
        </ul>
        <div class="form-inline my-2 my-lg-0">
          {% if request.user.is_staff %}
          <div class="btn-group mr-2">
            <a class="nav-link btn btn-danger" href="{% url 'core:admin-dashboard' %}">ADMIN</a>
          </div>
          {% endif %}
          {% if request.user.is_authenticated %}
          <div class="btn-group mr-2">
          <form action="{% url 'accounts:user-mode-switch' %}" method="post">
            {% csrf_token %}
            {% if request.user.mode == 'B' %}
                <button class="nav-link btn btn-outline-success">SWITCH TO SELLER</button>
            {% elif request.user.mode == 'S' %}
                <button class="nav-link btn btn-outline-success">SWITCH TO BUYER</button>
            {% endif %}
            </form>
          </div>
          <div class="btn-group mr-2">
            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Notifications <span class="badge badge-light">{{notifications.count}}</span></button>
            <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 38px, 0px); top: 0px; left: 0px; will-change: transform;">
              {% for notification in notifications %}
              <a class="dropdown-item" href="{{notification.redirect_url}}">{{notification.content}}
                <br><span><small>{{notification.timestamp|timesince}}</small></span>
              </a>
              <div clawss="dropdown-divider"></div>
              {% endfor %}
              <a class="dropdown-item" href="{% url 'core:notifications' %}">Show All Notifications</a>
            </div>
          </div>
          <div class="btn-group">
            <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{request.user.username.title}} </button>
            <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 38px, 0px); top: 0px; left: 0px; will-change: transform;">
              <a class="dropdown-item" href="{% url 'accounts:user_profile' %}">Profile</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
            </div>
          </div>
          {% else %}
          <a href="{% url 'accounts:login' %}" class="btn btn-outline-success my-2 my-sm-0 mx-1">Login</a>
          <a href="{% url 'accounts:register' %}" class="btn btn-outline-success my-2 my-sm-0 mx-1">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </div>
    </nav>

    {% block body %}
    {% endblock body %}
    <footer class="page-footer font-small blue" style="background-color: black;">	
      <div class="footer-copyright text-center py-4 text-white">	
        © 2022 Copyright: All Rights Reserved.	
        <br>	
        <h4><a href="{% url 'core:project_plan' %}" class="text text-danger">PROJECT PLAN ONLY FOR DEVs</a></h4>	
        <h5 class="text-warning">Last Build: {{build|timesince}}</h5>	
        <h5 class="text-warning">DEBUG: {{debug}}</h5>	
      </div>	
    </footer>
    <div class="modal fade" id="modal-analysis" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog  modal-lg" role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
              </div>
              <div id="analysis-data" class="modal-body">
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary">Save changes</button>
              </div>
          </div>
      </div>
  </div>
  <div class="modal" tabindex="-1" role="dialog"  id="infoModal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <p><strong>Please Wait, we are uploading the files to server...<br>Do not close the window...</strong></p>
        </div>
      </div>
    </div>
  </div>
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.10.0/jsoneditor.min.js" integrity="sha512-ruQAvFENqNvZOgUR7kldDYoQQLXs/CTx/ZJJhDpGKB5iqrhdq92S+P6sYsl6HCE+xTIFDhDo2FiZ3PJGKPWjWg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  </body>
  </body>
  {% block js %}
  {% endblock js %}
  <script src="https://cdn.tiny.cloud/1/cjb79ugu717829e6z3xuubd4o8s98in5vsytb7lp9fnzfw8d/tinymce/6/tinymce.min.js"
            referrerpolicy="origin"></script>
  <script>
    tinymce.init({
      selector: '.richtext_field',
      plugins: 'anchor autolink charmap codesample emoticons lists media searchreplace table visualblocks wordcount',
      toolbar: 'undo redo | bold italic underline strikethrough | align | numlist bullist indent outdent | emoticons charmap | removeformat',
      tinycomments_mode: 'embedded',
      tinycomments_author: 'Author name',
      statusbar: false,
      menubar: false,
      mergetags_list: [
        { value: 'First.Name', title: 'First Name' },
        { value: 'Email', title: 'Email' },
      ]
    });
  </script>
</html>

templates/scraper.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    BROWSER WORKING
</body>
</html>