api/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


app_name = 'api'

urlpatterns = [
    path('statistical-anaylsis/<str:product_type>/<str:title>/', views.statistical_analysis, name='statistical-analysis'),
    path('brochure-templates/<str:product_type>/', views.brochure_templates, name='brochure-templates'),

    path('users/<str:username>/products/', views.UserProductsView.as_view(), name='user-products'), #
    path('users/<str:username>/orders/', views.UserOrdersView.as_view(), name='user-orders'), #
    path('users/<str:username>/orders/recent/', views.UserRecentOrdersView.as_view(), name='user-recent-orders'), #
    path('users/<str:username>/brochures/', views.UserBrochureView.as_view(), name='user-brochures'), #
    path('users/<str:username>/market/', views.UserMarketingResults.as_view(), name='user-market'), #

    path('products/<int:product_id>/orders/', views.ProductOrdersView.as_view(), name='product-orders'),
    # path('products/<int:product_id>/feedback/', views.UserProductFeedbackView.as_view(), name='product-feedback'),
    path('products/<int:product_id>/<str:activity_type>/', views.product_activity, name='product-activity'),

    path('products/', views.ProductListView.as_view(), name='products'),
    path('orders/', views.OrdersView.as_view(), name='orders'),
    path('users/', views.UserListView.as_view(), name='users'),
    path('brochures/', views.BrochureListView.as_view(), name='brochures'),
    path('market/', views.MarketingResultsListView.as_view(), name='market-results'),
]

buyer/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'buyer'

urlpatterns = [
    path('client_dashboard/', views.client_dashboard, name='dashboard'),
    path('buy_product/<int:price_package_id>/', views.buy_product, name='buy-product'),
    path('feedback/<int:bought_package_id>/', views.give_feedback, name='give-feedback'),
]

core/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('redirect/', views.redirect_users, name='redirect'),
    path('explore/', views.explore, name='explore'),
    path('billing/', views.billing, name='billing'),
    path('about-us/', views.about, name='about-us'),
    path('notifications/', views.notifications, name='notifications'),

    path('product/search/', views.search_product, name='product-search'),
    path('product/<str:slug>/', views.view_product, name='product-view'),

    path('user/<str:username>/', views.view_user, name='user-view'),

    path('plan/', views.project_plan, name='project_plan'),
    path('stripe/webhook/', views.stripe_webhook, name='stripe_webhook'),

    path('admins/product/review/', views.admins_product_reivew, name='admin-product-review'),
    path('admins/dashboard/', views.admin_dashboard_view, name='admin-dashboard'),

    path('analysis/product/<int:product_id>/', views.product_analysis_view, name='product-analysis'),
    path('analysis/user/<str:username>/', views.user_analysis_view, name='user-analysis'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('accounts.urls')),
    path('', include('core.urls')),
    path('', include('seller.urls')),
    path('', include('buyer.urls')),
    path('', include('market.urls')),

    path('api/v1/', include('api.urls')),

    path('tinymce/', include('tinymce.urls')),

    path(
        'reset_password/',
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html'
        ),
        name="reset_password"
    ),
    path(
        'reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_sent.html'
        ),
        name="password_reset_done"
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_form.html'
        ),
        name="password_reset_confirm"
    ),
    path(
        'reset_password_complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name="password_reset_complete"
    ),
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='accounts/change_password.html',
            success_url = '/'
        ),
        name='change_password'
    ),


]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

market/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'market'

urlpatterns = [
    # path('product/<int:product_id>/brochure/', views.brochure_list, name='brochure-list'),
    path('product/<int:product_id>/brochure/<int:brochure_id>/', views.brochure_detail, name='brochure-detail'),
    path('product/<int:pk>/market/', views.marketing_platform_list, name='market-list'),
]

seller/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'seller'

urlpatterns = [
    path('seller_dashboard/', views.seller_dashboard, name='dashboard'),

    path('product/create/logo/', views.create_logo, name='create-logo'),
    path('product/create/template/', views.create_template, name='create-template'),
    path('product/create/software/', views.create_software, name='create-software'),
    path('product/create/api/', views.create_api, name='create-api'),

    path('product/update/<int:product_id>/logo/', views.update_logo, name='update-logo'),
    path('product/update/<int:product_id>/template/', views.update_template, name='update-template'),
    path('product/update/<int:product_id>/software/', views.update_software, name='update-software'),
    path('product/update/<int:product_id>/api/', views.update_api, name='update-api'),

    path('product/delete/<int:product_id>/', views.delete_product, name='delete-product'),

]

templates/components/product/buyer-dashboard-product-card.html
<div class="col-12">
    <div class="media m-3 text-muted">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" style="width: 64px; height: 64px;" src="{{bought_product.package.service.thumbnail.url}}" data-holder-rendered="true">
        <a style="text-decoration: none; color: black;" href="{% url 'core:product-view' bought_product.package.service.slug %}"><div class="media-body">
            <h5 class="mt-0"><strong class="d-block text-gray-dark">{{bought_product.package.service.title}}</strong></h5>
            <p class="mt-0">{{bought_product.package.service.get_description_text|truncatechars:200}}</p>
            <p class="mt-0"><strong>Purchased: </strong>{{bought_product.timestamp}}</p>
            {% if bought_product.package.service.product_type == 'A' %}
            <p class="mt-0"><strong>Token: </strong>{{bought_product.token}}</p>
            <p class="mt-0"><strong>Requests Left: </strong>{{bought_product.normal_requests_left}}</p>
            
            {% endif %}
        </div></a>
        <div class="ml-5 align-self-center px-3">
            {% if bought_product.package.service.product_type == 'A' %}
            <a href="{% url 'buyer:buy-product' bought_product.package.id %}" type="button" class="btn btn-warning font-weight-bold"><b>RE-BUY<br>Package</b></a>
            {% else %}
            {% if bought_product.package.service.get_product_obj.source_file %}
                <a href="{{bought_product.package.service.get_product_obj.source_file.url}}" type="button" class="btn btn-warning font-weight-bold"><b>DOWNLOAD<br>PRODUCT</b></a>
                {% else %}
                <a href="" type="button" class="btn btn-warning font-weight-bold"><b>DOWNLOAD<br>PRODUCT</b></a>
            {% endif %}
            {% endif %}
            <br><br>
            {% if not bought_product.is_feedback_given %}
            <a href="{% url 'buyer:give-feedback' bought_product.id %}" type="button" class="btn btn-dark font-weight-bold"><b>PROVIDE<br>FEEDBACK</b></a>
            {% endif %}
        </div>
    </div>
</div>

templates/components/product/private-product-card.html
<div class="card col-3 px-1 bg-white rounded box-shadow" >
    {% if product.thumbnail %}
    <img class="card-img-top p-2" src="{{product.thumbnail.url}}" style='max-height: 325px;' alt="Card image cap">
    {% else %}
    <img class="card-img-top p-2" src="" style='max-height: 325px;' alt="Image Not Found">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">{{product.title}}</h5>
        <div class="dropdown-divider"></div>
        <div class="">
            <span class="badge badge-warning float-start p-2">{{product.get_product_type_display.upper}}</span>
            {% if product.status == 'A' %}
            <span class="badge badge-success float-right p-2">{{product.get_status_display.upper}}</span>
            {% elif product.status == 'P' %}
            <span class="badge badge-warning float-right p-2">{{product.get_status_display.upper}}</span>
            {% elif product.status == 'D' %}
            <span class="badge badge-danger float-right p-2">{{product.get_status_display.upper}}</span>
            {% endif %}
        </div>
        <div class="dropdown-divider"></div>
        <div class="">
            {% if product.status != 'D' %}
                {% if product.product_type == 'L' %}
                <a href="{% url 'seller:update-logo' product.id %}" class="badge badge-warning float-start p-2 col-12 mt-2">UPDATE</a>
                {% elif product.product_type == 'H'%}
                <a href="{% url 'seller:update-template' product.id %}" class="badge badge-warning float-start p-2 col-12 mt-2">UPDATE</a>
                {% elif product.product_type == 'D' %}
                <a href="{% url 'seller:update-software' product.id %}" class="badge badge-warning float-start p-2 col-12 mt-2">UPDATE</a>
                {% elif product.product_type == 'A' %}
                <a href="{% url 'seller:update-api' product.id %}" class="badge badge-warning float-start p-2 col-12 mt-2">UPDATE</a>
                {% endif %}
                <a href="{% url 'seller:delete-product' product.id %}" class="badge badge-danger float-start p-2 col-12 my-2">DELETE</a>
            {% endif %}

            {% if product.status == 'A' %}
                <a href="{% url 'market:market-list' product.id %}" class="badge badge-info float-start p-2 col-12">MARKET</a>
                {% if product.product_type == 'L' %}
                <a href="{% url 'market:brochure-detail' product.id 3 %}" class="badge badge-success float-start p-2 col-12 my-2">DESIGN BROCHURE</a>
                {% elif product.product_type == 'H'%}
                <a href="{% url 'market:brochure-detail' product.id 2 %}" class="badge badge-success float-start p-2 col-12 mt-2">DESIGN BROCHURE</a>
                {% elif product.product_type == 'D' %}
                <a href="{% url 'market:brochure-detail' product.id 1 %}" class="badge badge-success float-start p-2 col-12 mt-2">DESIGN BROCHURE</a>
                {% endif %}
            {% endif %}
        </div>
        <div class="dropdown-divider"></div>
        <div class="">
            <h6>Impressions: {{product.impressions}} <i class="fa fa-solid fa-views"></i></h6>
            <h6>Clicks: {{product.clicks}} <i class="fa fa-solid fa-views"></i></h6>
        </div>
    </div>
</div>

templates/components/product/public-product-card.html
<div class ="col-2 my-1 col-md-2 col-sm-6">
    <div class="card">
        {% if product.thumbnail %}
        <img class="card-img-top card-image p-2" src="{{product.thumbnail.url}}" style='max-height: 325px;' alt="Card image cap">
        {% else %}
        <img class="card-img-top card-image p-2" src="" style='max-height: 325px;' alt="Image Not Found">
        {% endif %}
        <div class="card-body col-12">
            <a href="{% url 'core:user-view' product.owner.username %}">
                <h6 class="card-title mb-3">
                    <img class="rounded-circle mr-3" src="https://images.unsplash.com/photo-1544967082-d9d25d867d66?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80" 
                        style="width:30px; height:30px;" alt="">
                        <b>{{product.owner.username|upper}}</b>
                </h6>
            </a>
            <a href="{% url 'core:product-view' product.slug %}" class="card-title text-secondary"><h6>{{product.title}}</h6></a>
            <div class="dropdown-divider"></div>
            <div class="">
                <span class="fa fa-star checked float-start p-2">({{product.review_count}})</span>
                {% if product.product_type == 'A' %}
                <span style="background-color: tomato;" class="badge text-white float-right p-2">{{product.get_product_type_display.upper}}</span>
                {% elif product.product_type == 'L' %}
                <span style="background-color:darkgreen;" class="badge text-white float-right p-2">{{product.get_product_type_display.upper}}</span>
                {% elif product.product_type == 'H' %}
                <span style="background-color:darkslateblue;" class="badge text-white float-right p-2">{{product.get_product_type_display.upper}}</span>
                {% elif product.product_type == 'D' %}
                <span style="background-color:darkorange;"  class="badge text-white float-right p-2">{{product.get_product_type_display.upper}}</span>
            {% else %}

            {% endif %}
            </div>
        </div>
    </div>
</div>